import type { Review, Song } from "@/lib/types";

export const reviewQueue: Song[] = [
  {
    id: "q1",
    title: "After Midnight",
    artist: "Maya Sol",
    genre: "Alternative",
    language: "English",
    feedbackFocus: ["Hook Strength", "Production"],
    country: "United States",
    platform: "Spotify",
    link: "https://open.spotify.com/",
    coverUrl: "/covers/after-midnight.svg",
    accent: "#b9ff66",
    submittedAt: "2026-06-06",
  },
  {
    id: "q2",
    title: "Static Hearts",
    artist: "Night Archive",
    genre: "Rock",
    language: "English",
    feedbackFocus: ["Arrangement", "Mix"],
    country: "United Kingdom",
    platform: "YouTube",
    link: "https://www.youtube.com/",
    coverUrl: "/covers/static-hearts.svg",
    accent: "#ff8066",
    submittedAt: "2026-06-05",
  },
  {
    id: "q3",
    title: "Palm Reader",
    artist: "Theo Vale",
    genre: "Cumbia",
    language: "Spanish",
    feedbackFocus: ["Commercial Potential", "General Feedback"],
    country: "Canada",
    platform: "SoundCloud",
    link: "https://soundcloud.com/",
    coverUrl: "/covers/palm-reader.svg",
    accent: "#7b8cff",
    submittedAt: "2026-06-04",
  },
];

export const userSong: Song = {
  id: "mine-1",
  title: "Neon Weather",
  artist: "Carlos Jimenez",
  genre: "Indie",
  language: "Instrumental",
  feedbackFocus: ["Hook Strength", "Mix"],
  country: "United States",
  platform: "YouTube Music",
  link: "https://music.youtube.com/",
  coverUrl: "/covers/neon-weather.svg",
  accent: "#c7ff4f",
  submittedAt: "2026-05-28",
};

export const demoReviews: Review[] = [
  {
    id: "r1",
    songId: "mine-1",
    reviewer: "Anonymous listener",
    listenFull: true,
    addPlaylist: true,
    grabbedAttention: true,
    shareWithFriend: true,
    rating: 9,
    comment:
      "The texture in the intro pulled me in immediately. The vocal sits beautifully once the drums arrive.",
    qualityScore: 96,
    qualityPassed: true,
    createdAt: "2026-06-07",
  },
  {
    id: "r2",
    songId: "mine-1",
    reviewer: "Anonymous listener",
    listenFull: true,
    addPlaylist: false,
    grabbedAttention: true,
    shareWithFriend: true,
    rating: 8,
    comment:
      "Strong atmosphere. I would bring the first hook in a few seconds sooner, but the production feels finished.",
    qualityScore: 92,
    qualityPassed: true,
    createdAt: "2026-06-06",
  },
  {
    id: "r3",
    songId: "mine-1",
    reviewer: "Anonymous listener",
    listenFull: false,
    addPlaylist: false,
    grabbedAttention: false,
    shareWithFriend: false,
    rating: 6,
    comment:
      "The sound design is good, though the opening takes a little too long to establish where the song is going.",
    qualityScore: 95,
    qualityPassed: true,
    createdAt: "2026-06-05",
  },
  {
    id: "r4",
    songId: "mine-1",
    reviewer: "Anonymous listener",
    listenFull: true,
    addPlaylist: true,
    grabbedAttention: true,
    shareWithFriend: true,
    rating: 9,
    comment: "That bass movement is excellent. Easy playlist add for me.",
    qualityScore: 84,
    qualityPassed: true,
    createdAt: "2026-06-04",
  },
  {
    id: "r5",
    songId: "mine-1",
    reviewer: "Anonymous listener",
    listenFull: true,
    addPlaylist: true,
    grabbedAttention: true,
    shareWithFriend: false,
    rating: 8,
    qualityScore: 90,
    qualityPassed: true,
    createdAt: "2026-06-03",
  },
  {
    id: "r6",
    songId: "mine-1",
    reviewer: "Anonymous listener",
    listenFull: true,
    addPlaylist: false,
    grabbedAttention: true,
    shareWithFriend: false,
    rating: 7,
    comment:
      "Really clean mix. The transition near the end of the first minute was the moment that sold it.",
    qualityScore: 93,
    qualityPassed: true,
    createdAt: "2026-06-02",
  },
  {
    id: "r7",
    songId: "mine-1",
    reviewer: "Anonymous listener",
    listenFull: true,
    addPlaylist: true,
    grabbedAttention: true,
    shareWithFriend: true,
    rating: 9,
    qualityScore: 88,
    qualityPassed: true,
    createdAt: "2026-06-01",
  },
  {
    id: "r8",
    songId: "mine-1",
    reviewer: "Anonymous listener",
    listenFull: false,
    addPlaylist: false,
    grabbedAttention: false,
    shareWithFriend: false,
    rating: 6,
    comment:
      "Interesting palette, but the intro did not give me enough melodic information to stay engaged.",
    qualityScore: 94,
    qualityPassed: true,
    createdAt: "2026-05-31",
  },
  {
    id: "r9",
    songId: "mine-1",
    reviewer: "Anonymous listener",
    listenFull: true,
    addPlaylist: true,
    grabbedAttention: true,
    shareWithFriend: true,
    rating: 8,
    qualityScore: 91,
    qualityPassed: true,
    createdAt: "2026-05-30",
  },
  {
    id: "r10",
    songId: "mine-1",
    reviewer: "Anonymous listener",
    listenFull: true,
    addPlaylist: true,
    grabbedAttention: true,
    shareWithFriend: true,
    rating: 9,
    comment:
      "Memorable chorus and a great sense of space. I wanted a little more variation in the second verse.",
    qualityScore: 95,
    qualityPassed: true,
    createdAt: "2026-05-29",
  },
  {
    id: "r11",
    songId: "mine-1",
    reviewer: "Anonymous listener",
    listenFull: true,
    addPlaylist: false,
    grabbedAttention: true,
    shareWithFriend: false,
    rating: 7,
    qualityScore: 87,
    qualityPassed: true,
    createdAt: "2026-05-29",
  },
  {
    id: "r12",
    songId: "mine-1",
    reviewer: "Anonymous listener",
    listenFull: true,
    addPlaylist: true,
    grabbedAttention: true,
    shareWithFriend: true,
    rating: 8,
    comment: "Polished, distinct, and very replayable. The intro is the strongest part.",
    qualityScore: 89,
    qualityPassed: true,
    createdAt: "2026-05-28",
  },
];
